name = "testanki1"
pages_build_output_dir = "."
compatibility_date = "2024-09-23"

# KV 数据库绑定
[[kv_namespaces]]
binding = "SFX_NAMES"
id = "18013c9b94ae41fd92a371abd9d1c811"

# 内网连接现有的 Worker (无需公网 workers.dev)
[[durable_objects.bindings]]
name = "SFX_HUB"
class_name = "SfxHub"
script_name = "testanki1"
