name = "testanki1"
main = "src/index.js"
compatibility_date = "2024-09-23"

# 静态网页目录
[assets]
directory = "."
binding = "ASSETS"

# KV 绑定
[[kv_namespaces]]
binding = "SFX_NAMES"
id = "18013c9b94ae41fd92a371abd9d1c811"

# 免费版 SQLite Durable Object 绑定
[[durable_objects.bindings]]
name = "SFX_HUB"
class_name = "SfxHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SfxHub"]
