const groupedEquipments = {
    "炮塔": ["滑膛炮", "冰风暴", "火焰炮", "蝎子", "镭射炮", "火龙珠", "激光炮", "磁力炮", "雷暴炮", "海啸", "火箭炮", "轰天炮", "极速炮", "离子炮", "马格南", "电磁炮", "特斯拉"],
    "底盘": ["泰坦", "圣骑士", "猛犸象", "猎人中甲", "蜂王", "霍珀", "独裁者", "阿瑞斯", "十字军", "维京", "黄蜂轻甲"]
};

const groupedAugments = {
    "炮塔": ["空（炮塔）", "肾上腺素", "螺线管冷却", "拖延协议", "加速协议", "负能量场", "震荡冻结", "入侵瞄准处理器", "射击速度调节器", "干扰弹", "更快速的水平跟踪", "铀弹", "钨弹", "轻型电容器", "重型电容器", "治疗发射器", "纳米反应器", "支援纳米机器人", "宽带发射器", "吸血鬼纳米机器人", "精确瞄准系统", "超累积炮弹", "突击弹药", "穿甲弹", "燃烧弹", "分类弹药", "自动加农炮", "高容量弹鼓", "电子偶", "重炮手", "大口径短炮", "自适应重载（1）", "自适应重载（2）", "导弹发射器“旋风”", "远程火箭炸药", "鱼叉导弹", "加强炮架", "自动火药装载机", "电磁脉冲炮弹", "迫击炮", "导弹发射器“镭射”", "负场稳定", "等离子焰炬", "狂暴", "赫利俄斯", "等离子体加速器", "重型等离子炮", "稳定等离子体", "等离子涡轮加速器", "腐蚀混合物", "等离子发生器", "紧凑型坦克", "高压泵", "脉冲星", "电磁加速器“侦察机”", "超空间炮弹", "爆炸性炮弹", "爆炸弹头", "真空炮弹", "眩晕弹", "冷冻炮弹", "«霰弹枪» 炮弹", "导弹发射器 «九头蛇»", "导弹发射器 «浮士德»", "导弹发射器 «串联»", "超高速炮弹", "碎纸机", "猎人电子偶", "重型重炮手", "突击弹药库", "大口径颗粒", "电动炮塔", "致命混合物", "可持续纳米机器人", "导弹发射器 «流星»", "轰炸机", "左轮手枪", "破坏者", "注射冲击纳米机器人", "涅墨西斯", "螺栓", "类星体", "稳定混合物", "休克疗法", "露营者", "导弹发射器 «铜指虎»", "仿星器", "拳师", "«圣剑» 炮弹", "暴风雨", "卡隆炮", "大和", "电压增强", "“双发”射击模式", "“三连发”射击模式", "“刺剑”射击模式", "北极星", "自适应自动加农炮", "卓越（炮塔）", "凤凰（炮塔）"],
    "底盘": ["空（底盘）", "极端轻型结构", "爆破手", "工兵", "驱动器", "轻型结构", "重型结构", "耐寒性", "耐热性", "抗干扰器", "攻强免疫", "抗电磁脉冲", "抗眩晕", "抗热", "抗寒", "救生员", "工程师", "榴弹兵", "卓越（底盘）", "凤凰（底盘）"],
    "射击颜色": ["深红色", "岩浆", "幻影黑", "粉红色", "雪", "寒冷", "暗月", "毒（1）", "毒（2）", "太阳", "火", "血液", "日食", "水", "天空蓝", "虚空", "金", "紫罗兰色", "珊瑚礁", "电", "天空", "爆破手（绿）", "爆破手（红）", "神秘的红色", "黑暗", "暴力", "正午", "烟雾", "魔法"]
};

const groupedBackgroundColors = {
    "来自装备改造图标": ["蓝紫色", "蓝粉渐变色", "红色", "浅蓝色", "深蓝色", "粉色", "紫色", "黄色", "橙色", "火红色", "蓝色", "绿色", "黑色"],
    "来自射击颜色图标": ["爆破手（红）", "爆破手（绿）", "电", "毒（1）", "毒（2）", "粉红色", "寒冷", "黑暗", "幻影黑", "火", "金", "魔法", "日食", "珊瑚礁", "深红色", "神秘的红色", "水", "太阳", "天空", "天空蓝", "虚空", "雪", "血液", "岩浆", "正午", "紫罗兰色", "暴力", "暗月", "烟雾"]
};

const rawTranslationMap = {
    "炮塔": "Turret", "底盘": "Hull", "射击颜色": "Shot Effect",
    "来自装备改造图标": "From Augment Icons", "来自射击颜色图标": "From Shot Effect Icons",
    "滑膛炮": "Hammer", "冰风暴": "Freeze", "火焰炮": "Firebird", "蝎子": "Scorpion", "镭射炮": "Shaft", "火龙珠": "Ricochet", "激光炮": "Railgun", "磁力炮": "Isida", "雷暴炮": "Thunder", "海啸": "Tsunami", "火箭炮": "Striker", "轰天炮": "Smoky", "极速炮": "Vulcan", "离子炮": "Twins", "马格南": "Magnum", "电磁炮": "Gauss", "特斯拉": "Tesla",
    "泰坦": "Titan", "圣骑士": "Paladin", "猛犸象": "Mammoth", "猎人中甲": "Hunter", "蜂王": "Hornet", "霍珀": "Hopper", "独裁者": "Dictator", "阿瑞斯": "Ares", "十字军": "Crusader", "维京": "Viking", "黄蜂轻甲": "Wasp",
    "空（炮塔）": "Empty", "肾上腺素": "Adrenaline", "螺线管冷却": "Solenoid Cooling", "拖延协议": "Dilatory Protocol", "加速协议": "Acceleration Protocol", "负能量场": "Minus-field", "震荡冻结": "Shock freeze", "入侵瞄准处理器": "Hacked Aiming Processor", "射击速度调节器": "Shooting speed regulator", "干扰弹": "Jamming Rounds", "更快速的水平跟踪": "Reinforced aiming transmission", "铀弹": "Uranium Shells", "钨弹": "Tungsten Shells", "轻型电容器": "Light capacitors", "重型电容器": "Heavy capacitors", "治疗发射器": "Healing Emitters", "纳米反应器": "Nanomass reactor", "支援纳米机器人": "Support nanobots", "宽带发射器": "Broadband radiators", "吸血鬼纳米机器人": "Vampire Nanobots", "精确瞄准系统": "High-precision aiming system", "超累积炮弹": "Supercumulative rounds", "突击弹药": "Assault rounds", "穿甲弹": "Armor-piercing shells", "燃烧弹": "Incendiary rounds", "分类弹药": "Sorted Ammunition", "自动加农炮": "Autocannon", "高容量弹鼓": "High-capacity ammo clip", "电子偶": "Duplet", "重炮手": "Slugger", "大口径短炮": "Blunderbuss", "自适应重载（1）": "Adaptive reload (1)", "自适应重载（2）": "Adaptive reload (2)", "导弹发射器“旋风”": "Missile launcher \"Cyclone\"", "远程火箭炸药": "Remote rocket explosives", "鱼叉导弹": "Harpoon", "加强炮架": "Reinforced gun carriage", "自动火药装载机": "Automated gunpowder loading mechanism", "电磁脉冲炮弹": "EMP Rounds", "迫击炮": "Mortar", "导弹发射器 «镭射»": "Missile launcher «Uranium»", "负场稳定": "Minus-field stabilization", "等离子焰炬": "Plasma-torch", "狂暴": "Berserk", "赫利俄斯": "Helios", "等离子体加速器": "Plasma accelerators", "重型等离子炮": "Heavy plasmagun", "稳定等离子体": "Stabilized plasma", "等离子涡轮加速器": "Plasma Turbo Accelerators", "腐蚀混合物": "Corrosive mix", "等离子发生器": "Plasmatron", "紧凑型坦克": "Compact fuel tanks", "高压泵": "High-pressure pump", "脉冲星": "Pulsar", "电磁加速器“侦察机”": "Electromagnetic accelerator \"Scout\"", "超空间炮弹": "Hyperspace rounds", "爆炸性炮弹": "Explosive shells", "爆炸弹头": "Explosive warheads", "真空炮弹": "«Vacuum» shells", "眩晕弹": "Stun shells", "冷冻炮弹": "Cryo rounds", "«霰弹枪» 炮弹": "«Shotgun» rounds", "导弹发射器 «九头蛇»": "Missile launcher «Hydra»", "导弹发射器 «浮士德»": "Missile launcher «Faust»", "导弹发射器 «串联»": "Missile launcher «Tandem»", "超高速炮弹": "Hyperspeed Rounds", "碎纸机": "Shredder", "猎人电子偶": "Hunter Duplet", "重型重炮手": "Heavy Slugger", "突击弹药库": "Assault Magazine", "大口径颗粒": "Large Caliber Pellets", "电动炮塔": "Electroturret", "致命混合物": "Critical Mix", "可持续纳米机器人": "Sustainable Nanobots", "导弹发射器 «流星»": "Missile Launcher «Meteor»", "轰炸机": "Bombard", "左轮手枪": "Revolver", "破坏者": "Destroyer", "注射冲击纳米机器人": "Shock Nanobots Injection", "涅墨西斯": "Nemesis", "螺栓": "Bolter", "类星体": "Quasar", "稳定混合物": "Stable Mix", "休克疗法": "Shock therapy", "露营者": "Camper", "导弹发射器 «铜指虎»": "Missile launcher «Brass Knucles»", "仿星器": "Stellarator", "拳师": "Boxer", "«圣剑» 炮弹": "«Excalibur» rounds", "暴风雨": "Tempest", "卡隆炮": "Carronade", "大和": "Yamato", "电压增强": "Increased Voltage", "“双发”射击模式": "\"Duplet\" Firing Mode", "“三连发”射击模式": "\"Triplet\" Firing Mode", "“刺剑”射击模式": "\"Rapier\" Firing Mode", "北极星": "Polaris", "自适应自动加农炮": "Adaptive Autocannon", "卓越（炮塔）": "Excelsior", "凤凰（炮塔）": "Phoenix",
    "空（底盘）": "Empty", "极端轻型结构": "Extreme Lightweight Construction", "爆破手": "Blaster", "工兵": "Miner", "驱动器": "Driver", "轻型结构": "Lightweight Construction", "重型结构": "Heavyweight Construction", "耐寒性": "Cold Resistance", "耐热性": "Heat Resistance", "抗干扰器": "Jammer Immunity", "攻强免疫": "AP Immunity", "抗电磁脉冲": "EMP Immunity", "抗眩晕": "Stun Immunity", "抗热": "Heat Immunity", "抗寒": "Cold Immunity", "救生员": "Lifeguard", "工程师": "Engineer", "榴弹兵": "Grenadier", "卓越（底盘）": "Excelsior", "凤凰（底盘）": "Phoenix",
    "深红色": "Crimson", "岩浆": "Magma", "幻影黑": "Black", "粉红色": "Pink", "雪": "Snow", "寒冷": "Cold", "暗月": "Dark Moon", "毒（1）": "Toxic (1)", "毒（2）": "Toxic (2)", "太阳": "Sun", "火": "Fire", "血液": "Blood", "日食": "Eclipse", "水": "Aqua", "天空蓝": "Blue", "虚空": "Void", "金": "Gold", "紫罗兰色": "Violet", "珊瑚礁": "Coral Reef", "电": "Electric", "天空": "Sky", "爆破手（绿）": "Blaster (Green)", "爆破手（红）": "Blaster (Red)", "神秘的红色": "Mysterious Red", "黑暗": "Darkness", "暴力": "VioleNt", "正午": "Noon", "烟雾": "Smoke", "魔法": "Magic",
    "蓝紫色": "Blue-Purple", "蓝粉渐变色": "Blue-Pink Gradient", "红色": "Red", "浅蓝色": "Light Blue", "深蓝色": "Dark Blue", "粉色": "Pink", "紫色": "Purple", "黄色": "Yellow", "橙色": "Orange", "火红色": "Fiery Red", "蓝色": "Blue", "绿色": "Green", "黑色": "Black"
};
